name: React App CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend
